### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by pierredittgen** [kaisersly/scottmurray-d3-fr#2]
Bonjour,

Tout d'abord, merci pour cette traduction en français de qualité !
J'indique ici les quelques fautes que j'ai pu repérer durant ma lecture :
#5-enchainer-les-methodes.html
## La transmission
- Beaucoup de méthodes de D3, mais pas toutes, retourne une sélection -> retournent une sélection 
## Sans les chaînes
- Beurk ! Quel désorde -> Beurk ! Quel désordre
#6-lier-les-donnees.html
## Faites votre sélection
- Cette méthode jète un oeil au DOM -> Cette méthode jette un œil au DOM
- [...] et insert un élément p dans le DOM -> et insère un élément dans le DOM
- [...]  et insert un texte. -> [...]  et insère un texte.
#10-introduction-a-svg.html
## Styliser les éléments SVG
- vous pouvez les inclure svg dans ces sélecteurs -> vous pouvez inclure svg dans ces sélecteurs
## Transparence
- rgba() attends trois valeurs -> rgba() attend trois valeurs
- troisième cercle est égale à 0.2 or 20% -> troisième cercle est égale à 0.2 soit 20%
#13-faire-un-graphique-a-barres.html
## Étiquettes (ou labels)
- Ça semble familié ? -> Ça semble familier ?
#14-faire-un-nuage-de-points.html
## Prochains pas
- on s’est pas vraiment améliorer par rapport -> on ne s'est pas vraiment amélioré par rapport
#15-echelles.html
## Échelles
- sans représenation visuelle directe -> sans représentation visuelle directe
## Affiner le nuage
- (Ou preque toujours : Jetez un oeil -> (Ou presque toujours : Jetez un oeil
- Être bien réposé -> Être bien reposé
#16-axes.html
## Paramétrer un axe
- Ce g devient la séléction -> Ce g devient la sélection
## S’occuper des marques (ticks)
- et en a deduit  -> et en a déduit

Merci encore pour votre travail !

Pierre Dittgen

**Comment by kaisersly** [comment]
Bonjour Pierre,

merci de m'avoir indiqué ces erreurs, je corrige dès que j'ai le temps.

Bonne journée.

**Comment by kaisersly** [comment]
Bonjour Pierre,

ces erreurs sont - ENFIN - corrigées par le commit 5427004.

Merci encore, et bonne continuation.

**Comment by pierredittgen** [comment]
Bonne nouvelle !

Merci

2015-10-10 9:23 GMT+02:00 kaisersly notifications@github.com:
